import React, { Component } from 'react';
import { Link } from "react-router-dom";

class Welcome extends Component {
    // constructor?

    render() {
        return (
            <section id="intro">
                <h2>Welcome!</h2>
                <h3>Can you tell a Real Cat Photo from one generated by AI?</h3>
                <p>Play the game by guessing which of two Cat images is a real photo, and which is AI-generated.</p>
                <p>Do well, and your high score may be immortalized in the top 5 on the Score Board!</p>
                <Link to="/setup">Set up to play!</Link>
            </section>
        );
    }
}

export default Welcome; 
