import React, { Component } from 'react';
import { Link } from "react-router-dom";

class Welcome extends Component {
    // constructor?

    render() {
        return (
            <section id="intro">
                <h2>Welcome!</h2>
                <h3>Can you tell a Real Cat Photo from one generated by AI?</h3>
                <p><strong>TODO</strong> explain the rules</p>
                <p><strong>TODO</strong> Component styling!</p>
                <Link to="/setup">Set up to play!</Link>
            </section>
        );
    }
}

export default Welcome; 
